environment_path: /home/ali/anaconda3/envs/sf_env
installed_conda_packages:
- _libgcc_mutex
- _openmp_mutex
- absl-py
- aiohappyeyeballs
- aiohttp
- aiosignal
- alsa-lib
- altair
- annotated-types
- anyio
- aom
- argon2-cffi
- argon2-cffi-bindings
- arrow
- asttokens
- astunparse
- async-lru
- async-timeout
- attr
- attrs
- aws-c-auth
- aws-c-cal
- aws-c-common
- aws-c-compression
- aws-c-event-stream
- aws-c-http
- aws-c-io
- aws-c-mqtt
- aws-c-s3
- aws-c-sdkutils
- aws-checksums
- aws-crt-cpp
- aws-sdk-cpp
- azure-core-cpp
- azure-identity-cpp
- azure-storage-blobs-cpp
- azure-storage-common-cpp
- azure-storage-files-datalake-cpp
- babel
- beautifulsoup4
- blas
- blas-devel
- bleach
- bleach-with-css
- blinker
- brotli
- brotli-bin
- brotli-python
- bzip2
- c-ares
- ca-certificates
- cached-property
- cached_property
- cachetools
- cairo
- catalogue
- certifi
- cffi
- charset-normalizer
- click
- cloudpathlib
- cloudpickle
- colorama
- comm
- confection
- contourpy
- cpython
- cuda-crt-tools
- cuda-cudart
- cuda-cudart_linux-64
- cuda-cuobjdump
- cuda-cupti
- cuda-nvcc-tools
- cuda-nvdisasm
- cuda-nvrtc
- cuda-nvtx
- cuda-nvvm-tools
- cuda-version
- cudnn
- cusparselt
- cycler
- cymem
- cyrus-sasl
- cython-blis
- dav1d
- dbus
- debugpy
- decorator
- defusedxml
- deprecated
- docutils
- double-conversion
- exceptiongroup
- executing
- expat
- fastai
- fastcore
- fastdownload
- fastprogress
- ffmpeg
- filelock
- filetype
- flatbuffers
- fluidsynth
- font-ttf-dejavu-sans-mono
- font-ttf-inconsolata
- font-ttf-source-code-pro
- font-ttf-ubuntu
- fontconfig
- fonts-conda-ecosystem
- fonts-conda-forge
- fonttools
- fqdn
- freeglut
- freetype
- fribidi
- frozenlist
- fsspec
- gast
- gdk-pixbuf
- gettext
- gettext-tools
- gflags
- giflib
- gitdb
- gitpython
- glib
- glib-tools
- glog
- gmp
- gmpy2
- gnutls
- google-pasta
- graphite2
- grpcio
- gst-plugins-base
- gstreamer
- h11
- h2
- h5py
- harfbuzz
- hdf5
- hpack
- httpcore
- httpx
- hyperframe
- icu
- idna
- imath
- importlib-metadata
- importlib_resources
- ipykernel
- ipython
- isoduration
- jack
- jasper
- jedi
- jinja2
- joblib
- json5
- jsonpointer
- jsonschema
- jsonschema-specifications
- jsonschema-with-format-nongpl
- jupyter-lsp
- jupyter_client
- jupyter_core
- jupyter_events
- jupyter_server
- jupyter_server_terminals
- jupyterlab
- jupyterlab_pygments
- jupyterlab_server
- keras
- keyutils
- kivy
- kivy-garden
- kiwisolver
- krb5
- lame
- langcodes
- language-data
- lcms2
- ld_impl_linux-64
- lerc
- level-zero
- libabseil
- libaec
- libarrow
- libarrow-acero
- libarrow-dataset
- libarrow-substrait
- libasprintf
- libasprintf-devel
- libass
- libavif16
- libblas
- libbrotlicommon
- libbrotlidec
- libbrotlienc
- libcap
- libcblas
- libclang-cpp18.1
- libclang13
- libcrc32c
- libcublas
- libcudnn
- libcudnn-dev
- libcudss0
- libcufft
- libcufile
- libcups
- libcurand
- libcurl
- libcusolver
- libcusparse
- libde265
- libdeflate
- libdrm
- libedit
- libegl
- libev
- libevent
- libexpat
- libffi
- libflac
- libfreetype
- libfreetype6
- libgcc
- libgcc-ng
- libgcrypt-lib
- libgettextpo
- libgettextpo-devel
- libgfortran
- libgfortran-ng
- libgfortran5
- libgl
- libglib
- libglu
- libglvnd
- libglx
- libgomp
- libgoogle-cloud
- libgoogle-cloud-storage
- libgpg-error
- libgrpc
- libheif
- libhwloc
- libiconv
- libidn2
- libjpeg-turbo
- liblapack
- liblapacke
- libllvm18
- libllvm19
- liblzma
- liblzma-devel
- libmad
- libmagma
- libnghttp2
- libnl
- libnsl
- libntlm
- libnvjitlink
- libnvjpeg
- libogg
- libopenblas
- libopencv
- libopengl
- libopentelemetry-cpp
- libopentelemetry-cpp-headers
- libopenvino
- libopenvino-auto-batch-plugin
- libopenvino-auto-plugin
- libopenvino-hetero-plugin
- libopenvino-intel-cpu-plugin
- libopenvino-intel-gpu-plugin
- libopenvino-intel-npu-plugin
- libopenvino-ir-frontend
- libopenvino-onnx-frontend
- libopenvino-paddle-frontend
- libopenvino-pytorch-frontend
- libopenvino-tensorflow-frontend
- libopenvino-tensorflow-lite-frontend
- libopus
- libparquet
- libpciaccess
- libpng
- libpq
- libprotobuf
- libre2-11
- librsvg
- libsndfile
- libsodium
- libsqlite
- libssh2
- libstdcxx
- libstdcxx-ng
- libsystemd0
- libtasn1
- libthrift
- libtiff
- libtorch
- libudev1
- libunistring
- libunwind
- liburing
- libusb
- libutf8proc
- libuuid
- libuv
- libva
- libvorbis
- libvpx
- libwebp-base
- libxcb
- libxcrypt
- libxgboost
- libxkbcommon
- libxml2
- libxslt
- libzlib
- lz4-c
- marisa-trie
- markdown
- markdown-it-py
- markupsafe
- matplotlib
- matplotlib-base
- matplotlib-inline
- mdurl
- micromamba
- mistune
- ml_dtypes
- mpc
- mpfr
- mpg123
- mpmath
- multidict
- munkres
- murmurhash
- mysql-common
- mysql-libs
- namex
- narwhals
- nbclient
- nbconvert-core
- nbformat
- nccl
- ncurses
- nest-asyncio
- nettle
- networkx
- nlohmann_json
- nomkl
- notebook
- notebook-shim
- numpy
- ocl-icd
- openblas
- opencl-headers
- opencv
- openexr
- openh264
- openjpeg
- openldap
- openssl
- opentelemetry-api
- opt_einsum
- optree
- opusfile
- orc
- overrides
- p11-kit
- packaging
- pandas
- pandocfilters
- pango
- parso
- patsy
- pcre2
- pexpect
- pickleshare
- pillow
- pip
- pixman
- pkgutil-resolve-name
- platformdirs
- portaudio
- preshed
- prometheus-cpp
- prometheus_client
- prompt-toolkit
- propcache
- protobuf
- psutil
- pthread-stubs
- ptyprocess
- pugixml
- pulseaudio-client
- pure_eval
- py-opencv
- py-xgboost
- pyarrow
- pyarrow-core
- pybind11
- pybind11-global
- pycparser
- pydantic
- pydantic-core
- pydeck
- pygments
- pyparsing
- pyside6
- pysocks
- python
- python-dateutil
- python-fastjsonschema
- python-flatbuffers
- python-json-logger
- python-tzdata
- python_abi
- pytorch
- pytz
- pyyaml
- pyzmq
- qhull
- qrcode
- qt6-main
- rav1e
- rdma-core
- re2
- readline
- referencing
- requests
- rfc3339-validator
- rfc3986-validator
- rich
- rpds-py
- s2n
- scikit-learn
- scipy
- sdl2
- sdl2_image
- sdl2_mixer
- sdl2_ttf
- seaborn
- seaborn-base
- send2trash
- setuptools
- shellingham
- six
- sleef
- smart-open
- smart_open
- smmap
- snappy
- sniffio
- soupsieve
- spacy
- spacy-legacy
- spacy-loggers
- srsly
- stack_data
- statsmodels
- streamlit
- svt-av1
- sympy
- tbb
- tenacity
- tensorboard
- tensorboard-data-server
- tensorflow
- tensorflow-base
- tensorflow-estimator
- tensorflow-gpu
- tensorflow-hub
- termcolor
- terminado
- tf-keras
- thinc
- threadpoolctl
- tinycss2
- tk
- toml
- tomli
- torchvision
- torchvision-extra-decoders
- tornado
- tqdm
- traitlets
- triton
- typer
- typer-slim
- typer-slim-standard
- types-python-dateutil
- typing-extensions
- typing-inspection
- typing_extensions
- typing_utils
- tzdata
- ujson
- unicodedata2
- uri-template
- urllib3
- wasabi
- watchdog
- wayland
- wayland-protocols
- wcwidth
- weasel
- webcolors
- webencodings
- websocket-client
- werkzeug
- wheel
- wrapt
- x264
- x265
- xcb-util
- xcb-util-cursor
- xcb-util-image
- xcb-util-keysyms
- xcb-util-renderutil
- xcb-util-wm
- xgboost
- xkeyboard-config
- xorg-libice
- xorg-libsm
- xorg-libx11
- xorg-libxau
- xorg-libxcomposite
- xorg-libxcursor
- xorg-libxdamage
- xorg-libxdmcp
- xorg-libxext
- xorg-libxfixes
- xorg-libxi
- xorg-libxrandr
- xorg-libxrender
- xorg-libxscrnsaver
- xorg-libxshmfence
- xorg-libxtst
- xorg-libxxf86vm
- xz
- xz-gpl-tools
- xz-tools
- yaml
- yarl
- zeromq
- zipp
- zlib
- zstandard
- zstd
installed_micromamba_packages:
- List
- Name
- "\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\
  \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\
  \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\
  \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\
  \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\
  \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\
  \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\
  \u2500"
- _libgcc_mutex
- _openmp_mutex
- absl-py
- aiohappyeyeballs
- aiohttp
- aiosignal
- alsa-lib
- altair
- annotated-types
- anyio
- aom
- argon2-cffi
- argon2-cffi-bindings
- arrow
- asttokens
- astunparse
- async-lru
- async-timeout
- attr
- attrs
- aws-c-auth
- aws-c-cal
- aws-c-common
- aws-c-compression
- aws-c-event-stream
- aws-c-http
- aws-c-io
- aws-c-mqtt
- aws-c-s3
- aws-c-sdkutils
- aws-checksums
- aws-crt-cpp
- aws-sdk-cpp
- azure-core-cpp
- azure-identity-cpp
- azure-storage-blobs-cpp
- azure-storage-common-cpp
- azure-storage-files-datalake-cpp
- babel
- beautifulsoup4
- blas
- blas-devel
- bleach
- bleach-with-css
- blinker
- brotli
- brotli-bin
- brotli-python
- bzip2
- c-ares
- ca-certificates
- cached-property
- cached_property
- cachetools
- cairo
- catalogue
- certifi
- cffi
- charset-normalizer
- click
- cloudpathlib
- cloudpickle
- colorama
- comm
- confection
- contourpy
- cpython
- cuda-crt-tools
- cuda-cudart
- cuda-cudart_linux-64
- cuda-cuobjdump
- cuda-cupti
- cuda-nvcc-tools
- cuda-nvdisasm
- cuda-nvrtc
- cuda-nvtx
- cuda-nvvm-tools
- cuda-version
- cudnn
- cusparselt
- cycler
- cymem
- cyrus-sasl
- cython-blis
- dav1d
- dbus
- debugpy
- decorator
- defusedxml
- deprecated
- docutils
- double-conversion
- exceptiongroup
- executing
- expat
- fastai
- fastcore
- fastdownload
- fastprogress
- ffmpeg
- filelock
- filetype
- flatbuffers
- fluidsynth
- font-ttf-dejavu-sans-mono
- font-ttf-inconsolata
- font-ttf-source-code-pro
- font-ttf-ubuntu
- fontconfig
- fonts-conda-ecosystem
- fonts-conda-forge
- fonttools
- fqdn
- freeglut
- freetype
- fribidi
- frozenlist
- fsspec
- gast
- gdk-pixbuf
- gettext
- gettext-tools
- gflags
- giflib
- gitdb
- gitpython
- glib
- glib-tools
- glog
- gmp
- gmpy2
- gnutls
- google-pasta
- graphite2
- grpcio
- gst-plugins-base
- gstreamer
- h11
- h2
- h5py
- harfbuzz
- hdf5
- hpack
- httpcore
- httpx
- hyperframe
- icu
- idna
- imath
- importlib-metadata
- importlib_resources
- ipykernel
- ipython
- isoduration
- jack
- jasper
- jedi
- jinja2
- joblib
- json5
- jsonpointer
- jsonschema
- jsonschema-specifications
- jsonschema-with-format-nongpl
- jupyter-lsp
- jupyter_client
- jupyter_core
- jupyter_events
- jupyter_server
- jupyter_server_terminals
- jupyterlab
- jupyterlab_pygments
- jupyterlab_server
- keras
- keyutils
- kivy
- kivy-garden
- kiwisolver
- krb5
- lame
- langcodes
- language-data
- lcms2
- ld_impl_linux-64
- lerc
- level-zero
- libabseil
- libaec
- libarrow
- libarrow-acero
- libarrow-dataset
- libarrow-substrait
- libasprintf
- libasprintf-devel
- libass
- libavif16
- libblas
- libbrotlicommon
- libbrotlidec
- libbrotlienc
- libcap
- libcblas
- libclang-cpp18.1
- libclang13
- libcrc32c
- libcublas
- libcudnn
- libcudnn-dev
- libcudss0
- libcufft
- libcufile
- libcups
- libcurand
- libcurl
- libcusolver
- libcusparse
- libde265
- libdeflate
- libdrm
- libedit
- libegl
- libev
- libevent
- libexpat
- libffi
- libflac
- libfreetype
- libfreetype6
- libgcc
- libgcc-ng
- libgcrypt-lib
- libgettextpo
- libgettextpo-devel
- libgfortran
- libgfortran-ng
- libgfortran5
- libgl
- libglib
- libglu
- libglvnd
- libglx
- libgomp
- libgoogle-cloud
- libgoogle-cloud-storage
- libgpg-error
- libgrpc
- libheif
- libhwloc
- libiconv
- libidn2
- libjpeg-turbo
- liblapack
- liblapacke
- libllvm18
- libllvm19
- liblzma
- liblzma-devel
- libmad
- libmagma
- libnghttp2
- libnl
- libnsl
- libntlm
- libnvjitlink
- libnvjpeg
- libogg
- libopenblas
- libopencv
- libopengl
- libopentelemetry-cpp
- libopentelemetry-cpp-headers
- libopenvino
- libopenvino-auto-batch-plugin
- libopenvino-auto-plugin
- libopenvino-hetero-plugin
- libopenvino-intel-cpu-plugin
- libopenvino-intel-gpu-plugin
- libopenvino-intel-npu-plugin
- libopenvino-ir-frontend
- libopenvino-onnx-frontend
- libopenvino-paddle-frontend
- libopenvino-pytorch-frontend
- libopenvino-tensorflow-frontend
- libopenvino-tensorflow-lite-frontend
- libopus
- libparquet
- libpciaccess
- libpng
- libpq
- libprotobuf
- libre2-11
- librsvg
- libsndfile
- libsodium
- libsqlite
- libssh2
- libstdcxx
- libstdcxx-ng
- libsystemd0
- libtasn1
- libthrift
- libtiff
- libtorch
- libudev1
- libunistring
- libunwind
- liburing
- libusb
- libutf8proc
- libuuid
- libuv
- libva
- libvorbis
- libvpx
- libwebp-base
- libxcb
- libxcrypt
- libxgboost
- libxkbcommon
- libxml2
- libxslt
- libzlib
- lz4-c
- marisa-trie
- markdown
- markdown-it-py
- markupsafe
- matplotlib
- matplotlib-base
- matplotlib-inline
- mdurl
- micromamba
- mistune
- ml_dtypes
- mpc
- mpfr
- mpg123
- mpmath
- multidict
- munkres
- murmurhash
- mysql-common
- mysql-libs
- namex
- narwhals
- nbclient
- nbconvert-core
- nbformat
- nccl
- ncurses
- nest-asyncio
- nettle
- networkx
- nlohmann_json
- nomkl
- notebook
- notebook-shim
- numpy
- ocl-icd
- openblas
- opencl-headers
- opencv
- openexr
- openh264
- openjpeg
- openldap
- openssl
- opentelemetry-api
- opt_einsum
- optree
- opusfile
- orc
- overrides
- p11-kit
- packaging
- pandas
- pandocfilters
- pango
- parso
- patsy
- pcre2
- pexpect
- pickleshare
- pillow
- pip
- pixman
- pkgutil-resolve-name
- platformdirs
- portaudio
- preshed
- prometheus-cpp
- prometheus_client
- prompt-toolkit
- propcache
- protobuf
- psutil
- pthread-stubs
- ptyprocess
- pugixml
- pulseaudio-client
- pure_eval
- py-opencv
- py-xgboost
- pyarrow
- pyarrow-core
- pybind11
- pybind11-global
- pycparser
- pydantic
- pydantic-core
- pydeck
- pygments
- pyparsing
- pyside6
- pysocks
- python
- python-dateutil
- python-fastjsonschema
- python-flatbuffers
- python-json-logger
- python-tzdata
- python_abi
- pytorch
- pytz
- pyyaml
- pyzmq
- qhull
- qrcode
- qt6-main
- rav1e
- rdma-core
- re2
- readline
- referencing
- requests
- rfc3339-validator
- rfc3986-validator
- rich
- rpds-py
- s2n
- scikit-learn
- scipy
- sdl2
- sdl2_image
- sdl2_mixer
- sdl2_ttf
- seaborn
- seaborn-base
- send2trash
- setuptools
- shellingham
- six
- sleef
- smart-open
- smart_open
- smmap
- snappy
- sniffio
- soupsieve
- spacy
- spacy-legacy
- spacy-loggers
- srsly
- stack_data
- statsmodels
- streamlit
- svt-av1
- sympy
- tbb
- tenacity
- tensorboard
- tensorboard-data-server
- tensorflow
- tensorflow-base
- tensorflow-estimator
- tensorflow-gpu
- tensorflow-hub
- termcolor
- terminado
- tf-keras
- thinc
- threadpoolctl
- tinycss2
- tk
- toml
- tomli
- torchvision
- torchvision-extra-decoders
- tornado
- tqdm
- traitlets
- triton
- typer
- typer-slim
- typer-slim-standard
- types-python-dateutil
- typing-extensions
- typing-inspection
- typing_extensions
- typing_utils
- tzdata
- ujson
- unicodedata2
- uri-template
- urllib3
- wasabi
- watchdog
- wayland
- wayland-protocols
- wcwidth
- weasel
- webcolors
- webencodings
- websocket-client
- werkzeug
- wheel
- wrapt
- x264
- x265
- xcb-util
- xcb-util-cursor
- xcb-util-image
- xcb-util-keysyms
- xcb-util-renderutil
- xcb-util-wm
- xgboost
- xkeyboard-config
- xorg-libice
- xorg-libsm
- xorg-libx11
- xorg-libxau
- xorg-libxcomposite
- xorg-libxcursor
- xorg-libxdamage
- xorg-libxdmcp
- xorg-libxext
- xorg-libxfixes
- xorg-libxi
- xorg-libxrandr
- xorg-libxrender
- xorg-libxscrnsaver
- xorg-libxshmfence
- xorg-libxtst
- xorg-libxxf86vm
- xz
- xz-gpl-tools
- xz-tools
- yaml
- yarl
- zeromq
- zipp
- zlib
- zstandard
- zstd
installed_pip_packages:
- absl-py
- aiohappyeyeballs
- aiohttp
- aiosignal
- altair
- annotated-types
- anyio
- argon2-cffi
- argon2-cffi-bindings
- arrow
- asttokens
- astunparse
- async-lru
- async-timeout
- attrs
- babel
- beautifulsoup4
- bleach
- blinker
- blis
- Brotli
- cached-property
- cachetools
- catalogue
- certifi
- cffi
- charset-normalizer
- click
- cloudpathlib
- cloudpickle
- colorama
- comm
- confection
- contourpy
- cycler
- cymem
- debugpy
- decorator
- defusedxml
- Deprecated
- docutils
- exceptiongroup
- executing
- fastai
- fastcore
- fastdownload
- fastjsonschema
- fastprogress
- filelock
- filetype
- flatbuffers
- fonttools
- fqdn
- frozenlist
- fsspec
- gast
- gitdb
- GitPython
- gmpy2
- google-pasta
- grpcio
- h11
- h2
- h5py
- hpack
- httpcore
- httpx
- hyperframe
- idna
- importlib_metadata
- importlib_resources
- ipykernel
- ipython
- isoduration
- jedi
- Jinja2
- joblib
- json5
- jsonpointer
- jsonschema
- jsonschema-specifications
- jupyter_client
- jupyter_core
- jupyter-events
- jupyter-lsp
- jupyter_server
- jupyter_server_terminals
- jupyterlab
- jupyterlab_pygments
- jupyterlab_server
- keras
- Kivy
- Kivy-Garden
- kiwisolver
- langcodes
- language_data
- marisa-trie
- Markdown
- markdown-it-py
- MarkupSafe
- matplotlib
- matplotlib-inline
- mdurl
- mistune
- ml-dtypes
- mpmath
- multidict
- munkres
- murmurhash
- namex
- narwhals
- nbclient
- nbconvert
- nbformat
- nest_asyncio
- networkx
- notebook
- notebook_shim
- numpy
- opencv-python
- opencv-python-headless
- opentelemetry-api
- opt_einsum
- optree
- overrides
- packaging
- pandas
- pandocfilters
- parso
- patsy
- pexpect
- pickleshare
- pillow
- pip
- pkgutil_resolve_name
- platformdirs
- preshed
- prometheus_client
- prompt_toolkit
- propcache
- protobuf
- psutil
- ptyprocess
- pure_eval
- pyarrow
- pybind11
- pybind11_global
- pycparser
- pydantic
- pydantic_core
- pydeck
- Pygments
- pyparsing
- PySide6
- PySocks
- python-dateutil
- python-json-logger
- pytz
- PyYAML
- pyzmq
- qrcode
- referencing
- requests
- rfc3339_validator
- rfc3986-validator
- rich
- rpds-py
- scikit-learn
- scipy
- seaborn
- Send2Trash
- setuptools
- shellingham
- shiboken6
- six
- smart_open
- smmap
- sniffio
- soupsieve
- spacy
- spacy-legacy
- spacy-loggers
- srsly
- stack_data
- statsmodels
- streamlit
- sympy
- tenacity
- tensorboard
- tensorboard_data_server
- tensorflow
- tensorflow_estimator
- tensorflow-hub
- termcolor
- terminado
- tf_keras
- thinc
- threadpoolctl
- tinycss2
- toml
- tomli
- torch
- torchvision
- torchvision-extra-decoders
- tornado
- tqdm
- traitlets
- triton
- typer
- typer-slim
- types-python-dateutil
- typing_extensions
- typing-inspection
- typing_utils
- tzdata
- ujson
- unicodedata2
- uri-template
- urllib3
- wasabi
- watchdog
- wcwidth
- weasel
- webcolors
- webencodings
- websocket-client
- Werkzeug
- wheel
- wrapt
- xgboost
- yarl
- zipp
- zstandard
python_version: 3.10.17
