name: تثبيت المكتبات داخل GitHub Actions

on: [push]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: تثبيت Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: '3.10'

      - name: تثبيت المكتبات المطلوبة
        run: |
          conda install -c conda-forge googleapis-common-protos dill segno
          pip install googleapis-common-protos dill segno

      - name: التحقق من التثبيت
        run: |
          python -c "import googleapis_common_protos, dill, segno; print(' جميع المكتبات تعمل بنجاح!')"